name 'quast'
maintainer 'Eagle Genomics Ltd'
maintainer_email 'chef@eaglegenomics.com'
license 'apache2'
description 'Installs/Configures QUAST'
long_description 'Installs/Configures QUAST'
version '1.0.5'
source_url 'https://github.com/EagleGenomics-cookbooks/quast'
issues_url 'https://github.com/EagleGenomics-cookbooks/quast/issues'

depends 'build-essential'
depends 'java'
depends 'magic_shell'
depends 'apt'
