name 'QUAST'
maintainer 'Eagle Genomics Ltd'
maintainer_email 'chef@eaglegenomics.com'
license 'apache2'
description 'Installs/Configures QUAST'
long_description 'Installs/Configures QUAST'
version '0.1.0'
source_url 'https://github.com/EagleGenomics-cookbooks/QUAST'
issues_url 'https://github.com/EagleGenomics-cookbooks/QUAST/issues'

depends 'build-essential'
depends 'magic_shell'
depends 'poise-python', '~> 1.4.0'
